runtime: python39

service: glanceable-backend

env_variables:
  FLASK_ENV: production
  DATABASE_URL: duckdb:///../data/glanceable.duckdb
  USER_DATA_DATABASE_URL: duckdb:///../data/user_data.duckdb

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 