runtime: python312

env_variables:
  FLASK_ENV: production
  SECRET_KEY: x2pM_KHwnVP4sy6jYHqb4l9SVPSZx66QTHgiC0XBmZY
  DATABASE_URL: duckdb:///./glanceable.duckdb
  ANALYTICS_DATABASE_URL: duckdb:///./glanceable.duckdb
  WAREHOUSE_DATABASE_URL: duckdb:///./glanceable.duckdb
  ALLOWED_ORIGINS: https://glanceable.vercel.app,http://localhost:3000
  OPENAI_API_KEY: your-openai-api-key-here

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always 